### ISSUE TITLE
Click Action Redirection Problem

### ISSUE THREAD

**Issue by hellosunghyun** [utomic-media/directus-extension-field-actions#26]
Click Action is set to Open Link, and when clicked, it is not redirected directly to the link, but is redirected after accessing the item page.

https://user-images.githubusercontent.com/96941616/226640524-c498a739-9fc6-48e1-ae05-cbd409e044e2.mp4

**Comment by BenoitAverty** [comment]
Hello,
I have the same problem. I think it's because the "event.stopPropagation" is set on the action handler, but in the case of "open link" action, the handler does nothing and the "a" link is used.

Potentially this is a problem with the way directus makes a link on an item row. It could be more clean to fix this on directus side, but it'll take more time.

**Comment by Dominic-Marcelino** [comment]
I'll look into this within the next days. Should be fixed latest at the beginning of the next week 👍🏼
There's a leftover from a previous change
