### ISSUE TITLE
copy button dont show up and dont work

### ISSUE THREAD

**Issue by dominicbrunner** [utomic-media/directus-extension-field-actions#55]
Hi Dominic

Very nice project.

i have running Directus version 10.12.1 running in docker. 

The Link actions works and the icon for the link too. 

But for copy to clipboard doent work and the icon dont show up. Same in Display and UI. If i use the action in display i have a button in the table view but there is nothing in the clipboard. I Use a String field.

Is there something wrong int the settings?

cheers
Dominic

![directus_user](https://github.com/utomic-media/directus-extension-field-actions/assets/87392608/3701e2dd-daa1-4c03-9c26-d58b9b6a4df3)
![directus_setting](https://github.com/utomic-media/directus-extension-field-actions/assets/87392608/ce298dad-05e4-4725-a871-0a1ec2753348)

**Comment by Dominic-Marcelino** [comment]
Hi Dominic 👋🏼
Do you have a valid SSL-certificate and a https connection? Otherwise the clipboard API is disabled and we hide the buttons. 

In case of a local instance use 127.0.0.1 - this enables the clipboard api via http.

I’m thinking of changing this behaviour and displaying a disabled button instead but not 100% sure yet. Would be a better experience for admins but displaying a non-working functionality for users. But as it shouldn’t be the case that often so I’ll change it most likely with the upcoming version.

**Comment by dominicbrunner** [comment]
No i dont use ssl at the moment because i use it only internally. But localhost is no option.

That would be nice. 
I try to get it to work with ssl.

Thank you for your fast response.

**Comment by dominicbrunner** [comment]
You are right. I will move to ssl. Thanks a lot.
